version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: "mongodb"
    command: ["bin/bash","-c","mongoimport --db wanderlust --collection posts --file sample_posts.json --jsonArray"]
    ports:
      - "27017:27017"
    networks:
      - wanderlust
    restart: always

  backend:
    image: dcx369/wanderlust-backend
    container_name: "backend"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - CORS_ORIGIN=http://20.119.78.4:5173
      - FRONTEND_URL=http://20.119.78.4:5173
    ports:
      - "5000:5000"
    networks:
      - wanderlust
    restart: always

  frontend:
    image: dcx369/wanderlust-frontend
    container_name: "frontend"
    environment:
      - VITE_API_PATH=http://20.119.78.4:5000
    ports:
      - "5173:5173"
    networks:
      - wanderlust
    restart: always

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wanderlust
    restart: always

networks:
  wanderlust:
    driver: bridge
