services:
  mongodb:
    container_name: mongodb
    image: "dcx369/mongodb:latest"
    command: ["bin/bash","-c","mongoimport --db wanderlust --collection posts --file sample_posts.json --jsonArray"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - wanderlust_0
    restart: always

  backend:
    container_name: backend
    image: "dcx369/wanderlust-backend"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - CORS_ORIGIN=http://localhost:8080
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "5000:5000"
    networks:
      - wanderlust_0
    restart: always

  frontend:
    container_name: frontend
    image: "dcx369/wanderlust-frontend"
    environment:
      - VITE_API_PATH=http://localhost:8080/api
    ports:
      - "5173:5173"
    networks:
      - wanderlust_0
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wanderlust_0
    restart: always

networks:
  wanderlust_0:
    name: "wanderlust"
    driver: bridge

volumes:
  mongo_data:
